FROM alpine:latest
RUN apk update
RUN apk add --no-progress \
    php-bcmath \
    php-bz2 \
    php-calendar \
    php-cli \
    php-common \
    php-ctype \
    php-curl \
    php-dba \
    php-dbg \
    php-doc \
    php-dom \
    php-exif \
    php-ftp \
    php-gd \
    php-gettext \
    php-gmp \
    php-iconv \
    php-imap \
    php-intl \
    php-json \
    php-ldap \
    php-mcrypt \
    php-mssql \
    php-mysql \
    php-mysqli \
    php-odbc \
    php-openssl \
    php-pdo \
    php-pdo_dblib \
    php-pdo_mysql \
    php-pdo_odbc \
    php-pdo_pgsql \
    php-pdo_sqlite \
    php-pear \
    php-pgsql \
    php-phar \
    php-posix \
    php-pspell \
    php-shmop \
    php-snmp \
    php-soap \
    php-sockets \
    php-sqlite3 \
    php-sysvmsg \
    php-sysvsem \
    php-sysvshm \
    php-wddx \
    php-xml \
    php-xmlreader \
    php-xmlrpc \
    php-xsl \
    php-zip \
    php-zlib \
    git \
    openssl \
    openssh-client \
    ca-certificates
RUN export PATH=$PATH:/root/.composer/vendor/bin/:/php/bin
EXPOSE 8000
